### PR TITLE
Cleaning up some error reports from the validator

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Title casing titles.
2.  Adding missing files.
3.  Filling in a few link sections.

### CODE REVIEW

**Comment by DamienIrving** [comment]
@gvwilson Thanks for those edits. Will lessons that use the new lesson template (like this one) be linked to from the [lessons page](http://www.software-carpentry.org/lessons.html) on the website? And what will be the process for determining when a lesson is at a mature enough stage to be included on that page?

**Comment by DamienIrving** [comment]
The reason I ask is that my lesson has a few of the extras missing (e.g. notes for instructors, a motivation slide show). Do I have to complete all those missing pieces before the lesson can go up on the lessons page?

**Comment by gvwilson** [comment]
+1 to links from the lessons page - please send a PR.  No idea what the 
process will be - a conclave of wise elders examines the entrails of a 
chicken, or something like that.

**Comment by gvwilson** [comment]
Some of our lessons still don't have some of those things, so what we 
should do is work out a score (tied into the validator) so we can rate 
each lesson's finishedness.

**Pull request merged**
